[phases.setup]
nixPkgs = ['nodejs_18', 'python3', 'ffmpeg']

[phases.install]
cmds = [
  'cp -r backend/* .',
  'npm ci --production'
]

[phases.build]
cmds = [
  'chmod +x bin/yt-dlp'
]

[start]
cmd = 'node server.js'

[variables]
NODE_ENV = 'production'
PORT = '5002'
