[phases.setup]
nixPkgs = ['nodejs_18', 'python3', 'ffmpeg']

[phases.install]
cmds = [
  'cd backend',
  'npm ci --production'
]

[phases.build]
cmds = [
  'cd backend',
  'chmod +x bin/yt-dlp'
]

[start]
cmd = 'cd backend && node server.js'

[variables]
NODE_ENV = 'production'
PORT = '5002'
